{
 "title": "NetMeta Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "adhoc_query_filter", "query": "${VAR_ADHOC_QUERY_FILTER}" },
   {
    "name": "sampler",
    "label": "Source",
    "query": "SELECT DISTINCT IPv6NumToString(SamplerAddress) FROM flows_raw"
   },
   { "name": "adhoc", "label": "Custom filters" },
   { "name": "srcIP", "label": "Src IPv6" },
   { "name": "dstIP", "label": "Dst IPv6" },
   { "name": "nextHop", "label": "Next Hop IPv6" },
   { "name": "extra", "label": "Custom SQL" }
  ]
 },
 "panels": [
  {
   "title": "Total Flows Stored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "FlowReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count()\nFROM $table\nWHERE 1\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)",
     "rawQuery": "SELECT count() FROM default.flows_raw WHERE 1                    ",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  { "title": "Traffic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Packets ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sum(Packets * SamplingRate) / $interval AS Packets,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     sum(Packets * SamplingRate) / 1 AS Packets,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586086)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586091)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "IP Proto",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    Proto,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, Proto, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     Proto,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586104)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, Proto, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Ethernet Type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    '0x' || hex(EType) AS EType,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, EType, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 60) * 60) * 1000 as t,     '0x' || hex(EType) AS EType,     sum(Bytes * SamplingRate) * 8 / 60 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590509504)                     GROUP BY t, EType, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Raw Flows/s Per Host",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(*) / $interval AS Flows,\n    SamplerAddress\nFROM $table\nWHERE\n    $timeFilter\n    $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n    $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n    $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n    $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n    $conditionalTest(AND $extra, $extra)\n\nGROUP BY\n    t, SamplerAddress\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     count(*) / 1 AS Flows,     SamplerAddress FROM default.flows_raw WHERE     TimeReceived >= toDateTime(1590586121)      AND SamplerAddress = toIPv6('::85.190.150.169')                           GROUP BY     t, SamplerAddress ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Traffic per Next Hop",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    NextHop,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, NextHop\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     NextHop,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586125)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, NextHop ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Traffic per Ingress Interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SamplerAddress,\n    InIf,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, SamplerAddress, InIf, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     SamplerAddress,     InIf,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586129)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, SamplerAddress, InIf, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Traffic per Egress Interface",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SamplerAddress,\n    OutIf,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY t, SamplerAddress, OutIf, FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     SamplerAddress,     OutIf,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586137)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY t, SamplerAddress, OutIf, FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "TopK Protocol Graphs (expensive)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Top 10 Source Ports",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SrcPort,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE\n    $timeFilter\n    $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n    $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n    $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n    $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n    AND SrcPort IN (\n    SELECT SrcPort\n    FROM $table\n    WHERE $timeFilter\n    GROUP BY SrcPort\n    ORDER BY count(*) DESC\n    LIMIT 10)\n    $conditionalTest(AND $extra, $extra)\n\nGROUP BY\n    t,\n    SrcPort,\n    FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     SrcPort,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE     TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256)                             AND SrcPort IN (     SELECT SrcPort     FROM default.flows_raw     WHERE TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256)     GROUP BY SrcPort     ORDER BY count(*) DESC     LIMIT 10)        GROUP BY     t,     SrcPort,     FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top 10 Destination Ports",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    DstPort,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps,\n    if(FlowDirection == 1, 'out', 'in') AS FlowDirection\nFROM $table\nWHERE\n    $timeFilter\n    $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n    $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n    $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n    $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n    AND DstPort IN (\n    SELECT DstPort\n    FROM $table\n    WHERE $timeFilter\n    GROUP BY DstPort\n    ORDER BY count(*) DESC\n    LIMIT 10)\n    $conditionalTest(AND $extra, $extra)\n\nGROUP BY\n    t,\n    DstPort,\n    FlowDirection\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     DstPort,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps,     if(FlowDirection == 1, 'out', 'in') AS FlowDirection FROM default.flows_raw WHERE     TimeReceived >= toDateTime(1590588644)                             AND DstPort IN (     SELECT DstPort     FROM default.flows_raw     WHERE TimeReceived >= toDateTime(1590588644)     GROUP BY DstPort     ORDER BY count(*) DESC     LIMIT 10)        GROUP BY     t,     DstPort,     FlowDirection ORDER BY t",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  { "title": "Top Flows / Hosts (expensive)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Top Source IPs",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  SamplerAddress,\n  SrcAddr,\n  sum(Bytes * SamplingRate) / 1024 as Bytes\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY SamplerAddress, SrcAddr\nORDER BY Bytes DESC\nLIMIT 100\n",
     "rawQuery": "SELECT    SamplerAddress,   SrcAddr,   sum(Bytes * SamplingRate) / 1024 as Bytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586148)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY SamplerAddress, SrcAddr ORDER BY Bytes DESC LIMIT 100",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top Destination IPs",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  SamplerAddress,\n  DstAddr,\n  sum(Bytes * SamplingRate) / 1024 as Bytes\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY SamplerAddress, DstAddr\nORDER BY Bytes DESC\nLIMIT 100\n",
     "rawQuery": "SELECT    SamplerAddress,   DstAddr,   sum(Bytes * SamplingRate) / 1024 as Bytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586144)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY SamplerAddress, DstAddr ORDER BY Bytes DESC LIMIT 100",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top Flows",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  SamplerAddress,\n  SrcAddr,\n  DstAddr,\n  SrcPort,\n  DstPort,\n  Proto,\n  sum(Bytes * SamplingRate) / 1024 as Bytes\nFROM $table\nWHERE $timeFilter\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY SamplerAddress, SrcAddr, DstAddr, SrcPort, DstPort, Proto\nORDER BY Bytes DESC\nLIMIT 20\n",
     "rawQuery": "SELECT    SamplerAddress,   SrcAddr,   DstAddr,   SrcPort,   DstPort,   Proto,   sum(Bytes * SamplingRate) / 1024 as Bytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586152)    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY SamplerAddress, SrcAddr, DstAddr, SrcPort, DstPort, Proto ORDER BY Bytes DESC LIMIT 20",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  { "title": "Origin AS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Top Source ASNs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  SrcAS,\n  sum(Bytes * SamplingRate) / 1024 as Bytes\nFROM $table\nWHERE $timeFilter AND FlowDirection = 0\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY SrcAS\nORDER BY Bytes DESC\nLIMIT 100\n",
     "rawQuery": "SELECT    SrcAS,   sum(Bytes * SamplingRate) / 1024 as Bytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586169) AND FlowDirection = 0    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY SrcAS ORDER BY Bytes DESC LIMIT 100",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top Destination ASNs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  DstAS,\n  sum(Bytes * SamplingRate) / 1024 as Bytes\nFROM $table\nWHERE $timeFilter AND FlowDirection = 1\n  $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n  $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n  $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n  $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n  $conditionalTest(AND $extra, $extra)\nGROUP BY DstAS\nORDER BY Bytes DESC\nLIMIT 101",
     "rawQuery": "SELECT    DstAS,   sum(Bytes * SamplingRate) / 1024 as Bytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1590586174) AND FlowDirection = 1    AND SamplerAddress = toIPv6('::85.190.150.169')                  GROUP BY DstAS ORDER BY Bytes DESC LIMIT 101",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top 10 Source ASN",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SrcAS,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps\nFROM $table\nWHERE\n    $timeFilter\n    $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n    $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n    $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n    $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n    AND SrcAS IN (\n    SELECT SrcAS\n    FROM $table\n    WHERE $timeFilter AND FlowDirection = 0\n    GROUP BY SrcAS\n    ORDER BY count(*) DESC\n    LIMIT 10)\n    $conditionalTest(AND $extra, $extra)\nGROUP BY\n    t,\n    SrcAS\nORDER BY t, Bps",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     SrcAS,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps FROM default.flows_raw WHERE     TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256)                             AND SrcAS IN (     SELECT SrcAS     FROM default.flows_raw     WHERE TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256) AND FlowDirection = 0     GROUP BY SrcAS     ORDER BY count(*) DESC     LIMIT 10)       GROUP BY     t,     SrcAS ORDER BY t, Bps",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  },
  {
   "title": "Top 10 Destination ASN",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    DstAS,\n    sum(Bytes * SamplingRate) * 8 / $interval AS Bps\nFROM $table\nWHERE\n    $timeFilter\n    $conditionalTest(AND SamplerAddress = toIPv6($sampler), $sampler)\n    $conditionalTest(AND SrcAddr = toIPv6('$srcIP'), $srcIP)\n    $conditionalTest(AND DstAddr = toIPv6('$dstIP'), $dstIP)\n    $conditionalTest(AND NextHop = toIPv6('$nextHop'), $nextHop)\n    AND DstAS IN (\n    SELECT DstAS\n    FROM $table\n    WHERE $timeFilter AND FlowDirection = 1\n    GROUP BY DstAS\n    ORDER BY count(*) DESC\n    LIMIT 10)\n    $conditionalTest(AND $extra, $extra)\nGROUP BY\n    t,\n    DstAS\nORDER BY t, Bps",
     "rawQuery": "SELECT     (intDiv(toUInt32(TimeReceived), 1) * 1) * 1000 as t,     DstAS,     sum(Bytes * SamplingRate) * 8 / 1 AS Bps FROM default.flows_raw WHERE     TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256)                             AND DstAS IN (     SELECT DstAS     FROM default.flows_raw     WHERE TimeReceived BETWEEN toDateTime(1590589695) AND toDateTime(1590590256) AND FlowDirection = 1     GROUP BY DstAS     ORDER BY count(*) DESC     LIMIT 10)       GROUP BY     t,     DstAS ORDER BY t, Bps",
     "round": "0s",
     "table": "flows_raw"
    }
   ]
  }
 ]
}